# Generated by Django 4.0.4 on 2022-06-08 22:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(default=uuid.UUID('0682e8d5-b06f-4516-a9cc-d9520be7d558'), max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.CharField(default=uuid.UUID('98f049d3-361a-4679-a273-837a014c0260'), max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
        ),
    ]
